@echo off
echo Testing FAT and exFAT speed...

echo - exFAT with 32K cluster...
mkfat.py G: -c 32k -t exfat >exercise_exfat.log && python -m cProfile -s cumtime stress.py -p15 -t 25 --fix G: >>exercise_exfat.log

echo - exFAT with 8K cluster...
mkfat.py G: -c 8k -t exfat >>exercise_exfat.log && python -m cProfile -s cumtime stress.py -p15 -t 25 --fix G: >>exercise_exfat.log

echo - exFAT with 512 cluster...
mkfat.py G: -c 512 -t exfat >>exercise_exfat.log && python -m cProfile -s cumtime stress.py -p15 -t 25 --fix G: >>exercise_exfat.log

echo - FAT with 32K cluster...
mkfat.py G: -c 32k -t fat32 >exercise_fat.log && python -m cProfile -s cumtime stress.py -p15 -t 25 --fix G: >>exercise_fat.log

echo - FAT with 8K cluster...
mkfat.py G: -c 8k -t fat32 >>exercise_fat.log && python -m cProfile -s cumtime stress.py -p15 -t 25 --fix G: >>exercise_fat.log

echo - FAT with 512 cluster...
mkfat.py G: -c 512 -t fat32 >>exercise_fat.log && python -m cProfile -s cumtime stress.py -p15 -t 25 --fix G: >>exercise_fat.log

echo End.
